# Generated by Django 6.0.7 on 2026-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_km', models.CharField(max_length=200, verbose_name='ចំណងជើង (ខ្មែរ)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('subtitle_km', models.CharField(blank=True, max_length=300, verbose_name='អត្ថបទរង (ខ្មែរ)')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (English)')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='រូបភាព')),
                ('button_text_km', models.CharField(blank=True, max_length=60, verbose_name='អក្សរលើប៊ូតុង (ខ្មែរ)')),
                ('button_text_en', models.CharField(blank=True, max_length=60, verbose_name='Button text (English)')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='តំណភ្ជាប់')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់')),
                ('is_active', models.BooleanField(default=True, verbose_name='បង្ហាញ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
