# Generated by Django 6.0.7 on 2026-08-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_km', models.CharField(max_length=100, verbose_name='ឈ្មោះ (ខ្មែរ)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_km', models.CharField(max_length=255, verbose_name='ចំណងជើង (ខ្មែរ)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt_km', models.CharField(max_length=300, verbose_name='សេចក្តីសង្ខេប (ខ្មែរ)')),
                ('excerpt_en', models.CharField(max_length=300, verbose_name='Excerpt (English)')),
                ('content_km', models.TextField(verbose_name='ខ្លឹមសារពេញ (ខ្មែរ)')),
                ('content_en', models.TextField(verbose_name='Full content (English)')),
                ('thumbnail', models.ImageField(upload_to='news/thumbnails/%Y/%m/', verbose_name='រូបភាពគម្រប')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ព័ត៌មានលេចធ្លោ')),
                ('is_published', models.BooleanField(default=True, verbose_name='បោះពុម្ពផ្សាយ')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទផ្សាយ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='banners.newscategory')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
