# Generated by Django 6.0.7 on 2026-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_newscategory_news_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text_en',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Button text (English)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text_km',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='អក្សរលើប៊ូតុង (ខ្មែរ)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='រូបភាព'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='តំណភ្ជាប់'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Subtitle (English)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle_km',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='អត្ថបទរង (ខ្មែរ)'),
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
