# Generated by Django 6.0.7 on 2026-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_remove_news_category_remove_newsimage_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title_km',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ចំណងជើង (ខ្មែរ)'),
        ),
    ]
