# Generated by Django 5.2.7 on 2026-08-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_km', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description_km', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(help_text='Start date/time of the event.')),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location_km', models.CharField(blank=True, max_length=255)),
                ('location_en', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
